"""Public, side-effect-free Python AIR pass framework contracts."""

from .api import (
    AIRAttribute,
    AIRObjectId,
    CURRENT_MODULE,
    CURRENT_PASS_UNIT,
    AnalysisPass,
    AnalysisExecutionResult,
    AnalysisRequest,
    AnalysisResult,
    IRUnitRef,
    ModuleView,
    MutableModuleView,
    PassExecutionResult,
    PassManagerResult,
    PreservedAnalyses,
    TransformResult,
    TransformationPass,
    UnitSelector,
    SourcePosition,
)
from .manager import AIRPassManager
from .pipeline_hooks import (
    HookExecutionResult,
    ManagerSegmentExecution,
    NativeBarrierExecutionResult,
    NativeBarrierOutcome,
    NativeBarrierStep,
    PassInstrumentation,
    PassPipelineConfig,
    PipelinePoint,
)
from .diagnostics import AIRLocation, Diagnostic, DiagnosticSeverity

__all__ = [
    "AIRLocation",
    "AIRAttribute",
    "AIRObjectId",
    "AIRPassManager",
    "AnalysisPass",
    "AnalysisExecutionResult",
    "AnalysisRequest",
    "AnalysisResult",
    "CURRENT_MODULE",
    "CURRENT_PASS_UNIT",
    "Diagnostic",
    "DiagnosticSeverity",
    "IRUnitRef",
    "HookExecutionResult",
    "ManagerSegmentExecution",
    "ModuleView",
    "MutableModuleView",
    "PassExecutionResult",
    "PassInstrumentation",
    "PassPipelineConfig",
    "PassManagerResult",
    "PreservedAnalyses",
    "PipelinePoint",
    "NativeBarrierExecutionResult",
    "NativeBarrierOutcome",
    "NativeBarrierStep",
    "TransformResult",
    "TransformationPass",
    "UnitSelector",
    "SourcePosition",
]
